package clustering.algorithms;
/**
 * Implements the {@link Clustering} interface. 
 * Clusters are generated using the occurenceTable by the {@link #createClusters()} method.
 * @author Lefas Aristeidis
 */
public abstract class OccurenceClustering implements Clustering {
	protected float occurenceTable[][];
	protected int[] clusters;

	
	public OccurenceClustering(float[][] occurenceTable){
		this.occurenceTable = occurenceTable;
	}
	/**
	 * Clears the array with the cluster assignments.
	 */
	public void clear() {
		clusters = null;
	}
	/**
	 * Generates the cluster assignments. 
	 * @return An array containing the cluster assignment for each entity. 
	 */
	protected abstract int[] createClusters();
	/**
	 * Returns the cluster assignments. 
	 * Clusters are generated by the {@link #createClusters()} function.
	 * @return An array containing the cluster assignment for each entity. 
	 */
	
	public int[] returnClusters() {
		if (clusters==null){
			clusters = createClusters();
		}
		return clusters;
	}
	
}
